// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPZfHwBPGMHyP3i9JWhj2eLruVQpfN-_Y',
    appId: '1:721648668341:web:624c93f2fe30fd4f9138fc',
    messagingSenderId: '721648668341',
    projectId: 'my-minimal-socialmedia',
    authDomain: 'my-minimal-socialmedia.firebaseapp.com',
    storageBucket: 'my-minimal-socialmedia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA8QOTe3jnlUJvTJuI2YYVDEAWDDGq9w4',
    appId: '1:721648668341:android:f02938bd27a821049138fc',
    messagingSenderId: '721648668341',
    projectId: 'my-minimal-socialmedia',
    storageBucket: 'my-minimal-socialmedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAihGD3op8FngIPiq4NeetSsRoopUohi_8',
    appId: '1:721648668341:ios:7c1384a8be2445439138fc',
    messagingSenderId: '721648668341',
    projectId: 'my-minimal-socialmedia',
    storageBucket: 'my-minimal-socialmedia.appspot.com',
    iosBundleId: 'com.example.minimalsocialmedia',
  );
}
